server:
  port: 6688

spring:
  application:
    name: helium-codegen
  profiles:
    # 具体的数据源，在子配置文件中指定
    # 为了安全考虑，可以另外复制出来一个 local 配置文件，不要放在版本控制系统中
    active: datasource,local
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
