server:
  port: 6688

# !!! 指定数据库类型，可选值有【mysql、postgresql】
databaseArch: mysql

spring:
  application:
    name: helio-generator
  datasource:
    # MySQL
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helio_generator?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # PostgreSQL
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/helio_generator
#    username: postgre
#    password: helio

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
