#代码生成器，配置信息

mainPath=cc.uncarbon
#包名
package=cc.uncarbon.module
#模块名
moduleName=sys
#表前缀(类名不会包含表前缀)
tablePrefix=tb_

#类型转换，配置信息
tinyint=Integer
smallint=Integer
mediumint=Integer
int=Integer
integer=Integer
bigint=Long
float=Float
double=Double
decimal=BigDecimal
bit=Boolean
bool=Boolean

char=String
varchar=String
tinytext=String
text=String
mediumtext=String
longtext=String

date=LocalDate
datetime=LocalDateTime
timestamp=LocalDateTime

int8=Long
int4=Integer
int2=Integer
numeric=BigDecimal
